Update patch set 1
Patch Set 1: Code-Review-1

too many errors in compilation http://nexus.jenkins.progmaticlab.com:8082/jenkins_logs/gerrit/22/61622/1/check_15526/build-centos/output-compile-centos.log

g++ -o build/production/vnsw/agent/kstate/kstate_handler.o -c -Wall -Werror -Wsign-compare -O3 -g -Wno-narrowing -Wno-conversion-null -Wno-unused-local-typedefs -DRAPIDJSON_NAMESPACE=contrail_rapidjson -DLINUX -Ibuild/production -Ibuild/production/base/sandesh -Isrc/contrail-common/base/sandesh -Ibuild/production/dns -Icontroller/src/dns -Ibuild/production/http/client -Isrc/contrail-common/http/client -Ibuild/production/ifmap -Icontroller/src/ifmap -Ibuild/production/schema -Isrc/contrail-api-client/schema -Ibuild/production/sandesh -Icontroller/src/sandesh -Ibuild/production/vnsw/agent -Icontroller/src/vnsw/agent -Ibuild/production/vnsw/agent/oper -Icontroller/src/vnsw/agent/oper -Ibuild/production/vnsw/agent/cmn -Icontroller/src/vnsw/agent/cmn -Ibuild/production/vnsw/agent/uve -Icontroller/src/vnsw/agent/uve -Ibuild/production/vrouter/sandesh -Ivrouter/sandesh -Ibuild/production/vnsw/agent/nexthop_server -Icontroller/src/vnsw/agent/nexthop_server -Ibuild/production/vnsw/agent/vrouter/ksync/linux -Icontroller/src/vnsw/agent/vrouter/ksync/linux -Ibuild/production/tools/sandesh/library/common -Isrc/contrail-common/sandesh/library/common -Ibuild/include/thrift -Ivrouter/include -Icontroller/src -Ibuild/include -Isrc/contrail-common -Icontroller/lib controller/src/vnsw/agent/kstate/kstate_handler.cc
In file included from vrouter/include/nl_util.h:17:0,
                 from vrouter/utils/nl_util.c:31:
vrouter/include/vr_info.h:11:18: error: expected â€˜)â€™ before numeric constant
 #define DPDK     2
                  ^
vrouter/include/vr_info.h:26:31: note: in expansion of macro â€˜DPDKâ€™
     X(INFO_DDP, info_get_ddp, DPDK) \
                               ^
vrouter/include/vr_info.h:97:3: warning: data definition has no type or storage class [enabled by default]
 } vr_info_msg_en;
   ^
vrouter/include/vr_info.h:114:5: error: expected specifier-qualifier-list before â€˜vr_info_msg_enâ€™
     vr_info_msg_en msginfo;
     ^
In file included from vrouter/utils/nl_util.c:31:0:
vrouter/include/nl_util.h:313:34: error: expected declaration specifiers or â€˜...â€™ before â€˜vr_info_msg_enâ€™
         int marker, int inst_id, vr_info_msg_en msginfo, int buffsz,


.....

Patch-set: 1
Reviewer: Gerrit User 382 <382@c72cd27d-1743-4a55-84a4-cd13b8400c52>
Label: Code-Review=-1